version: '3.8'

services:
  php:
    build: ./images/php
    links:
      - postgresql
    networks:
      - docker_env
  postgresql:
    image: postgres:16-alpine3.17
    environment:
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}"
      - POSTGRES_USER:"${POSTGRES_USER}"
    volumes:
      - postgresdb:/usr/src/data/db
    networks:
      - docker_env
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - ${port}:${port}
    volumes:
      - ./images/php/project_docker/hello.dev:/usr/src/project/hello.dev


      - ./logs/nginx-access.log:/usr/src/log/nginx/nginx-access.log
      - ./logs/nginx-error.log:/usr/src/log/nginx/nginx-error.log
    networks:
      - docker_env
  adminer:
    image: adminer:latest
    networks:
      - docker_env
volumes:
  postgresdb:
networks:
  docker_env:
    driver: bridge