version: '3.8'

services:
    php:
        build: 
            ./php
        links:
            - postgresql
        networks:
            - dockernet_prod
        container_name:
            php_prod
    postgresql:
        image: postgres:16-alpine3.17
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
        volumes:
            - postgresdb:/usr/src/data/db
        networks:
            - dockernet_prod
        container_name:
            postgresql_prod
    nginx:
        build:
            context: .
            dockerfile: nginx/Dockerfile
        ports:
            - ${port}:80
        volumes:
            - ./php/project:/usr/src/project/
            - ./logs/nginx/:/usr/src/log/nginx/
        networks:
            - dockernet_prod
        container_name:
            nginx_prod
volumes:
  postgresdb:
networks:
  dockernet_prod:
    driver: bridge